/*
 * Mojang Session Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JoinServerRequest {
    #[serde(rename = "accessToken")]
    pub access_token: String,
    #[serde(rename = "selectedProfile")]
    pub selected_profile: uuid::Uuid,
    #[serde(rename = "serverId")]
    pub server_id: String,
}

impl JoinServerRequest {
    pub fn new(access_token: String, selected_profile: uuid::Uuid, server_id: String) -> JoinServerRequest {
        JoinServerRequest {
            access_token,
            selected_profile,
            server_id,
        }
    }
}


