openapi: 3.0.0

info:
  title: Mojang Session Server
  version: 1.0.0

servers:
  - url: https://sessionserver.mojang.com

components:
  schemas:
    Error:
      type: object
      properties:
        path:
          type: string
        error:
          type: string
        errorMessage:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          pattern: ^[a-zA-Z0-9_]{2,16}$
        properties:
          type: array
          items:
            $ref: '#/components/schemas/UserProperty'
      required:
        - id
        - name
        - properties

    UserProperty:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
          format: byte
        signature:
          type: string
          format: byte
      required:
        - name
        - value

paths:
  /blockedservers:
    get:
      operationId: getBlockedServers
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                type: string

  /session/minecraft/hasJoined:
    get:
      operationId: hasJoinedServer
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: serverId
          in: query
          required: true
          schema:
            type: string
        - name: ip
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '204':
          description: No Content

  /session/minecraft/join:
    post:
      operationId: joinServer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                selectedProfile:
                  type: string
                  format: uuid
                serverId:
                  type: string
              required:
                - accessToken
                - selectedProfile
                - serverId
      responses:
        '200':
          description: Ok
        '4XX':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /session/minecraft/profile/{userId}:
    get:
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: unsigned
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '204':
          description: No Content
        '4XX':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
